apiVersion: apps/v1
kind: Deployment
metadata:
  name: lonewolf
  labels:
    app: lonewolf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lonewolf
  template:
    metadata:
      labels:
        app: lonewolf
    spec:
      containers:
        - name: lonewolf
          image: ghcr.io/dufelizardo/lonewolf:6f840c53081b26d7057b369119a3212602895741
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
